### ISSUE TITLE
セットアップ中にSQLiteDatabaseLockedException

### ISSUE THREAD

**Issue by daisy1754** [hyurumi/8koma-client#105]
今のとこ臼山端末でのみ確認されてるエラー
https://deploygate.com/users/hachiko/apps/com.appspot.hachiko_schedule/devices/11101

```
android.database.sqlite.SQLiteDatabaseLockedException: database is locked
    at android.database.sqlite.SQLiteDatabase.dbopen(Native Method)
    at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1132)
    at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1083)
    at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:241)
    at com.appspot.hachiko_schedule.db.UserTableHelper.getHachikoId(UserTableHelper.java:110)
    at com.appspot.hachiko_schedule.friends.FriendsFragment$1.onClick(FriendsFragment.java:51)
    at android.view.View.performClick(View.java:3631)
    at android.view.View$PerformClick.run(View.java:14333)
    at android.os.Handler.handleCallback(Handler.java:605)
    at android.os.Handler.dispatchMessage(Handler.java:92)
    at android.os.Looper.loop(Looper.java:137)
    at android.app.ActivityThread.main(ActivityThread.java:4516)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:511)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:991)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:758)
    at dalvik.system.NativeStart.main(Native Method)
```

**Comment by daisy1754** [comment]
詳しくわかんないけど，セットアップ完了前に友達一覧画面にいっちゃうのが問題かしら

**Comment by daisy1754** [comment]
duplicate to #139
