### ISSUE TITLE
人誘ったらおちる

### ISSUE THREAD

**Issue by hyurumi** [hyurumi/8koma-client#87]
10-15 20:41:31.514: ERROR/AndroidRuntime(5686): FATAL EXCEPTION: IntentService[GcmIntentService]
        java.lang.IllegalArgumentException
        at java.util.ArrayList.<init>(ArrayList.java:73)
        at com.appspot.hachiko_schedule.push.GcmIntentService.requestUnknownFriendInfo(GcmIntentService.java:147)
        at com.appspot.hachiko_schedule.push.GcmIntentService.sendInviteNotification(GcmIntentService.java:82)
        at com.appspot.hachiko_schedule.push.GcmIntentService.onHandleIntent(GcmIntentService.java:66)
        at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:156)
        at android.os.HandlerThread.run(HandlerThread.java:60)

**Comment by daisy1754** [comment]
反省

**Comment by daisy1754** [comment]
fix #87 とかコミットメッセージに入れると自動で閉じるのか，アツい
